#ifndef MEDIAPLAYERSTYLING_H_INCLUDED
#define MEDIAPLAYERSTYLING_H_INCLUDED

#define _MUSIC_PLAYER_FOREGROUND_COLOR wxColor(25, 125, 255)
#define _MUSIC_PLAYER_FOREGROUND_DISABLE_COLOR wxColor(100, 100, 100)
#define _MUSIC_PLAYER_BACKGROUND_COLOR wxColor(30, 30, 30)
#define _MUSIC_PLAYER_FONT wxFont(8, wxFONTFAMILY_TELETYPE, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL )

#define _MUSIC_CONTROL_FOREGROUND_COLOR wxColor(25, 125, 255)
#define _MUSIC_CONTROL_FOREGROUND_DISABLE_COLOR wxColor(100, 100, 100)
#define _MUSIC_CONTROL_BACKGROUND_COLOR wxColor(0, 0, 0)
#define _MUSIC_CONTROL_FONT wxFont(8, wxFONTFAMILY_TELETYPE, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL )

#endif // MEDIAPLAYERSTYLING_H_INCLUDED
